"use client";

import { motion } from "framer-motion";
import {
  BookOpen,
  TrendingUp,
  DollarSign,
  Home,
  Clock,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";

const articles = [
  {
    category: "Market Trends",
    title: "Housing Market 2025: AI-Powered Forecast and Analysis",
    excerpt:
      "GeeniAI analyzes market data to reveal upcoming trends in property values, interest rates, and buyer behavior.",
    readTime: "5 min read",
    icon: TrendingUp,
  },
  {
    category: "Investment",
    title: "Real Estate Investing: AI Tools for Maximum ROI",
    excerpt:
      "Discover how HomeGeeni helps investors identify properties with the highest potential returns through automated valuations.",
    readTime: "7 min read",
    icon: DollarSign,
  },
  {
    category: "Home Buying",
    title: "Send Offers and Manage Showings with HomeGeeni",
    excerpt:
      "Learn how HomeGeeni's platform streamlines the home buying process from search to closing with automated tools.",
    readTime: "6 min read",
    icon: Home,
  },
];

const ContentHubSection = () => {
  return (
    <section className="py-32 bg-gray-50">
      <div className="container px-4">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          {" "}
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-gray-200 mb-8 shadow-sm">
            <BookOpen className="w-4 h-4 text-blue-600" />
            <span className="text-sm font-medium text-gray-700">
              GeeniAI Blog
            </span>
          </div>
          <h2 className="text-5xl md:text-6xl font-light mb-6 text-gray-900 tracking-tight">
            AI-Enhanced Insights
            <br />
            <span className="font-medium">Generated by AI</span>
          </h2>{" "}
          <p className="text-xl text-gray-500 max-w-3xl mx-auto mb-3 font-light leading-relaxed">
            Some of our blog content is generated or enhanced using artificial
            intelligence to provide timely, informative, and engaging real
            estate insights for agents, buyers, and sellers alike.
          </p>
          <p className="text-sm text-gray-400 max-w-2xl mx-auto mb-8 italic">
            While we strive for accuracy, AI-generated content may occasionally
            contain errors or outdated information. All information should be
            independently verified and does not constitute legal, financial, or
            real estate advice.
          </p>
        </motion.div>

        {/* Featured Articles */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16 max-w-7xl mx-auto">
          {articles.map((article, index) => (
            <motion.article
              key={article.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="group cursor-pointer"
            >
              <div className="bg-white rounded-2xl p-8 hover:shadow-lg transition-all duration-300 border border-gray-100">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-xl bg-gray-100 flex items-center justify-center">
                    <article.icon className="w-5 h-5 text-gray-700" />
                  </div>
                  <span className="text-sm font-medium text-gray-500">
                    {article.category}
                  </span>
                </div>

                <h3 className="text-xl font-medium mb-4 text-gray-900 group-hover:text-blue-600 transition-colors leading-tight">
                  {article.title}
                </h3>

                <p className="text-gray-500 mb-6 leading-relaxed font-light">
                  {article.excerpt}
                </p>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <Clock className="w-4 h-4" />
                    {article.readTime}
                  </div>
                  <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-blue-600 group-hover:translate-x-1 transition-all" />
                </div>
              </div>
            </motion.article>
          ))}
        </div>

        {/* Stats & CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="bg-white rounded-3xl p-12 text-center border border-gray-100 max-w-5xl mx-auto"
        >
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
            <div>
              <div className="text-4xl font-light text-gray-900 mb-2">500+</div>
              <div className="text-gray-500 font-light">
                AI-Generated Articles
              </div>
            </div>
            <div>
              <div className="text-4xl font-light text-gray-900 mb-2">24/7</div>
              <div className="text-gray-500 font-light">Content Updates</div>
            </div>
            <div>
              <div className="text-4xl font-light text-gray-900 mb-2">98%</div>
              <div className="text-gray-500 font-light">Accuracy Rate</div>
            </div>
          </div>

          <h3 className="text-3xl font-light mb-4 text-gray-900">
            Never Miss Important Market Updates
          </h3>
          <p className="text-gray-500 mb-8 max-w-2xl mx-auto font-light leading-relaxed">
            Subscribe to our AI-powered content hub and get personalized
            insights delivered to your inbox.
          </p>

          <Button
            size="lg"
            className="bg-gray-900 hover:bg-gray-800 text-white px-8 py-6 text-lg rounded-xl transition-all duration-200"
          >
            Explore All Content
          </Button>
        </motion.div>
      </div>
    </section>
  );
};

export default ContentHubSection;
